# theme = "monokai_pro_spectrum"
theme = "stylix"

[editor]
line-number = "relative"
mouse       = true
cursorline  = true
rulers      = [100]
auto-info = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
# end-of-line-diagnostics = "hlnt"

# [editor.inline-diagnostics]
# cursor-line = "warning"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render      = true
character   = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0

[editor.statusline]
left      = ["spinner", "mode", "file-modification-indicator", "read-only-indicator"]
center    = ["version-control", "file-name"]
right     = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

# [editor.whitespace.render]
# space = "none"
# tab = "all"
# tappad = "none"
# nbsp = "none"
# nnbsp = "none"
# newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-r      = ":config-reload"
C-s      = ":w" # Maps the Ctrl-s to the typable command :w which is an alias for :write (save file)
A-j      = ["search_selection" ,"extend_search_next"]
C-q      = ":bc"
C-A-l    = ":format"
C-o      = ":open ~/.config/helix/config.toml" # Maps the Ctrl-o to opening of the helix config file
"esc"    = ["collapse_selection", "keep_primary_selection"]
"ret"    = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
C-S-up   = ["extend_to_line_bounds", "delete_selection", "move_line_up", "goto_line_start", "paste_before", "goto_line_start"]
C-S-down = ["extend_to_line_bounds", "delete_selection", "move_line_down", "goto_line_start", "paste_before", "goto_line_start"]

[keys.normal.space]
i = ":toggle inline-diagnostics.cursor-line"

[keys.insert]
A-c =["move_prev_word_start", ":pipe /home/plasmaa0/.config/helix/close_tag.sh", "move_next_word_start", "move_char_right", "move_char_right", "insert_mode"]
# "esc" = ["normal_mode", ":w", ":run-shell-command ./build.sh"]
# j = { k = "normal_mode" } # Maps `jk` to exit insert mode
