[[language]]
name = "typescript"

[[language]]
name = "javascript"

[[language]]
name = "json"

[[language]]
name = "html"

[[language]]
name = "python"
auto-format = true
[language.formatter]
command = "black"
args = [
"-", # stdin
"--quiet",
"--line-length=79",
]

[[language]]
name = "latex"
formatter = { command = 'prettier', args = ["--parser", "latex-parser"] }
auto-format = true
indent = { tab-width = 4, unit = "\t" }
# config = { texlab = { auxDirectory = "build", build = { forwardSearchAfter = true, onSave = true, executable = "tectonic", args = [ "-X", "compile", "%f", "--synctex", "--keep-logs", "--keep-intermediates", "--outdir=build", "-Zshell-escape", ] }, chktex = { onEdit = true, onOpenAndSave = true }, forwardSearch = { executable = "zathura", args = [ "--synctex-forward", "%l:1:%f", "%p" ] } } }

[language-server.texlab.config.texlab]
auxDirectory = "build"

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true
onEdit = true

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:%c:%f", "%p" ]

# executable = "okular"
# args = ["--unique", "file:%p#src:%l%f"]

[language-server.texlab.config.texlab.build]
forwardSearchAfter = true
onSave = true

executable = "latexmk"
args = [
 "-pdf",
 "-interaction=nonstopmode",
 "-synctex=1",
 "-shell-escape",
 "-output-directory=build",
 "%f"
 ]

# executable = "tectonic"
# args = [
#  "-X",
#  "compile",
#  "%f",
#  "--synctex",
#  "--keep-logs",
#  "--keep-intermediates",
#  "--outdir=build",
#  "-Zshell-escape",
#  ]
