keys:
  - &admin age19dupq0mzy5fzgktuaghetv06g5mzxe3r93sklsnn36nplxpuhy9qdxwsdv
  - &machine age1sv5x6m9hfxd0dn8nzxdddyfsl2vm47vsckxqz38s8rad7racm5csyml94g
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *machine
